name: "spotify-frame"
description: "Server side for spotify-frame"
version: "0.1.36"
slug: "spotify_frame"
init: false
arch:
  - aarch64
startup: application
homeassistant_api: true
services:
  - mqtt:need
ports:
  8000/tcp: 8000
map:
  - type: addon_config
    read_only: False
schema:
  ota_github_repo: str
  github_token: password
  ota_storage_dir: str
  ota_host_ipv4: str
  ota_http_port: str
  ota_poll_interval_secs: str
  mqtt_client_id: str
  mqtt_keep_alive_secs: str
  media_player_proxy_base_url: str
  log_level: str?
  rocket_config: str?
image: "ghcr.io/ramesius/{arch}-spotify-frame"
