name: "spotify-frame"
description: "Server side for spotify-frame"
version: "0.1.25"
slug: "spotify_frame"
init: false
arch:
  - aarch64
startup: services
homeassistant_api: false
map:
  - type: addon_config
    read_only: False
schema:
  ota_github_repo: str
  ota_github_token: str
  github_token: str
  ota_storage_dir: str
  ota_host_ipv4: str
  ota_http_port: str
  ota_poll_interval_secs: str
  mqtt_broker_host: str
  mqtt_broker_port: str
  mqtt_client_id: str
  mqtt_username: str
  mqtt_password: str
  mqtt_keep_alive_secs: str
  log_level: str?
image: "ghcr.io/ramesius/{arch}-spotify-frame"
