name: "Liams Yoto sync tool"
description: "Liams Yoto sync tool."
version: "0.1.17"
slug: "liams_yoto_sync_tool"
init: false
arch:
  - aarch64
startup: services
homeassistant_api: false
map:
  - type: media
    read_only: False
  - type: addon_config
    read_only: False
schema:
  config_file_path: "str"
  track_cache_path: "str?"
  auth_store_path: "str?"
  spotify_client_id: str
  yoto_dev_client_id: str
image: "ghcr.io/ramesius/{arch}-liams-yoto-sync-tool"
